---
# tasks file for hmpps-delius-core-oracle-client-installer

- name: Get our artifacts from S3
  include: copy-artifacts.yml
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact

- name: Install artifacts
  yum:
    name: "{{ artifact.dest|default('/tmp/' + artifact.name) }}"
    state: present
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact

- name: Configure git credential store
  git_config:
    name: credential.helper
    scope: global
    value: store

- name: Configure git credentials
  template:
    src: git-credentials.j2
    dest: ~/.git-credentials

- name: Clean up after ourselves
  file:
    state: absent
    path: "{{ artifact.dest|default('/tmp/' + artifact.name) }}"
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact