---
# tasks file for hmpps-delius-core-oracle-client-installer

- name: Get our artifacts from S3
  include: copy-artifacts.yml
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact

- name: Install artifacts
  yum:
    name: "{{ artifact.dest|default('/tmp/' + artifact.name) }}"
    state: present
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact

- name: Clean up after ourselves
  file:
    state: absent
    path: "{{ artifact.dest|default('/tmp/' + artifact.name) }}"
  with_items: "{{ artifacts }}"
  loop_control:
    loop_var: artifact